### ISSUE TITLE
Dedicated server fails to start [Fabric 120.1 0.3.1]

### ISSUE THREAD

**Issue by TigerWalts** [Tejty/GameDiscs#2]
**Describe the bug**
Dedicated server fails to start. No crash report.
Fabric tries to load a client-only class.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run on a dedicated server

**Expected behaviour**
Server starts.

**Screenshots**
N/A

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - ModLoader: Fabric 0.16.9
 - Mod Version: 0.3.1

**Additional context**

```
[05:30:14] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'gamediscs' at 'net.tejty.gamediscs.GameDiscsMod'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.9.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_437
        at net.tejty.gamediscs.item.ItemRegistry.<clinit>(ItemRegistry.java:17) ~[GameDiscs-0.3.1-fabric.jar:?]
        at net.tejty.gamediscs.GameDiscsMod.onInitialize(GameDiscsMod.java:17) ~[GameDiscs-0.3.1-fabric.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_437
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.tejty.gamediscs.item.ItemRegistry.<clinit>(ItemRegistry.java:17) ~[GameDiscs-0.3.1-fabric.jar:?]
        at net.tejty.gamediscs.GameDiscsMod.onInitialize(GameDiscsMod.java:17) ~[GameDiscs-0.3.1-fabric.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 6 more
```

`net/minecraft/class_437` maps to `net.minecraft.client.gui.screens.Screen`

The class loader is eagerly loading classes even when behind a guard clause.

https://github.com/Tejty/GameDiscs/blob/410bb8ae0284b0eac5de0f52136944cf8712c2c6/src/main/java/net/tejty/gamediscs/item/ItemRegistry.java#L16-L18

When `ItemRegistry` is loaded the class loader sees that the constructor for `GamingConsoleItem` may get called and so it loads that class.

https://github.com/Tejty/GameDiscs/blob/410bb8ae0284b0eac5de0f52136944cf8712c2c6/src/main/java/net/tejty/gamediscs/item/custom/GamingConsoleItem.java#L22-L25

In `GamingConsoleItem` both `net.minecraft.client.MinecraftClient` and `GamingConsoleScreen` are invoked. The class loader ignores the guard clause (it cannot be evaluated at this point) and when it tries to load `GamingConsoleScreen` it errors as that class extends `net.minecraft.client.gui.screens.Screen`.

---

Annotating `GamingConsoleScreen` as client only may be enough to prevent it being eagerly loaded on a dedicated server:

- https://wiki.fabricmc.net/documentation:fabric_loader#class_loading_and_transformation

**Comment by Tejty** [comment]
This mod is not server compatible yet

**Comment by wolfieboy09** [comment]
Well, it's not "compatible" because we're calling client code stuff on the server @Tejty 😭

**Comment by HanHanDeYaYa** [comment]
> 这个 mod 还不兼容服务器

This mod does not indicate "@Environment (EnvType.CLIENT)" in the GUI class, resulting in an error, please modify it (can you also modify fabric1.20.1 at the same time after modification, don't only modify the new version)

**Comment by HanHanDeYaYa** [comment]
> This mod is not server compatible yet

The following is the code that should be added to the GUI class, please delete the love in the code and copy：
❤@❤E❤n❤v❤i❤r❤o❤n❤m❤e❤n❤t (EnvType.CLIENT)

**Comment by HanHanDeYaYa** [comment]
> Well, it's not "compatible" because we're calling client code stuff on the server [@Tejty](https://github.com/Tejty) 😭

Trouble adding client-only annotations for GUI classes“❤@❤E❤n❤v❤i❤r❤o❤n❤m❤e❤n❤t (EnvType.CLIENT)”

**Comment by wolfieboy09** [comment]
Hi, it's me. I'm close to finish the server crash fix, just need to not procrastinate :sob:
it's just data components and it's up

**Comment by Tejty** [comment]
Now fixed in 0.3.2
