### ISSUE TITLE
[NeoForge 1.21.1] High scores cannot be set after reloading a world

### ISSUE THREAD

**Issue by EnderTurret** [Tejty/GameDiscs#3]
**Environment**: NeoForge 21.1.90 (Minecraft 1.21.1)  
**Mod version**: 0.3.1a

Basically — at what appears to be random times — high scores can no longer be set on a given console.
I'm assuming it's when reloading a world since that's when data components are most likely to be deserialized, which is (I believe) what is triggering this problem.
Since data components are clearly involved, this does not affect 1.20.1 (which does not have them).

Here's a snippet of the log from when I encountered the issue:

```
[22Dec2024 00:29:53.853] [Server thread/ERROR] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: Failed to process a synchronized task of the payload: gamediscs:update_best_score
java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.21.1-20240808.144430-srg.jar%23333!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[client-1.21.1-20240808.144430-srg.jar%23333!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[client-1.21.1-20240808.144430-srg.jar%23333!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:872) ~[client-1.21.1-20240808.144430-srg.jar%23333!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:170) ~[client-1.21.1-20240808.144430-srg.jar%23333!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[client-1.21.1-20240808.144430-srg.jar%23333!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:855) ~[client-1.21.1-20240808.144430-srg.jar%23333!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:849) ~[client-1.21.1-20240808.144430-srg.jar%23333!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[client-1.21.1-20240808.144430-srg.jar%23333!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:821) ~[client-1.21.1-20240808.144430-srg.jar%23333!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:826) ~[client-1.21.1-20240808.144430-srg.jar%23333!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:712) ~[client-1.21.1-20240808.144430-srg.jar%23333!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21.1-20240808.144430-srg.jar%23333!/:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.UnsupportedOperationException
	at MC-BOOTSTRAP/com.google.common@32.1.2-jre/com.google.common.collect.ImmutableMap.put(ImmutableMap.java:781) ~[guava-32.1.2-jre.jar%23122!/:?]
	at TRANSFORMER/gamediscs@0.3.1a-neoforge/net.tejty.gamediscs.item.custom.GamingConsoleItem.setBestScore(GamingConsoleItem.java:50) ~[gamediscs-0.3.1a-neoforge.jar%23400!/:?]
	at TRANSFORMER/gamediscs@0.3.1a-neoforge/net.tejty.gamediscs.networking.packet.SetBestScorePacket.lambda$updateBestScore$0(SetBestScorePacket.java:30) ~[gamediscs-0.3.1a-neoforge.jar%23400!/:?]
	at TRANSFORMER/neoforge@21.1.90/net.neoforged.neoforge.network.handling.ServerPayloadContext.enqueueWork(ServerPayloadContext.java:32) ~[neoforge-21.1.90-universal.jar%23334!/:?]
	at TRANSFORMER/gamediscs@0.3.1a-neoforge/net.tejty.gamediscs.networking.packet.SetBestScorePacket.updateBestScore(SetBestScorePacket.java:25) ~[gamediscs-0.3.1a-neoforge.jar%23400!/:?]
	at TRANSFORMER/neoforge@21.1.90/net.neoforged.neoforge.network.handling.MainThreadPayloadHandler.lambda$handle$0(MainThreadPayloadHandler.java:16) ~[neoforge-21.1.90-universal.jar%23334!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:60) ~[client-1.21.1-20240808.144430-srg.jar%23333!/:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 14 more
```

I've taken a look at the code and the reason for this is almost certainly the storing of `HashMap` in the data component.
For context, data components are supposed to be *immutable* — when you want to modify one, you have to replace the existing one on the `ItemStack`.
Moreover, `Codec`s generally return immutable data structures (such as `ImmutableMap` as seen in the error stack trace).

I believe the following change should resolve the problem:

```diff
     public void setBestScore(ItemStack stack, String game, int score, Player player) {
-        BestScoreComponent component = stack.get(DataComponentRegistry.BEST_SCORE);
-        if (component == null) {
-            component = new BestScoreComponent(new HashMap<>(), player.getStringUUID());
-        } else if (!component.stringUUID().equals(player.getStringUUID())) {
+        BestScoreComponent component = stack.get(DataComponentRegistry.BEST_SCORE, new BestScoreComponent(Map.of(), player.getStringUUID()));
+        if (!component.stringUUID().equals(player.getStringUUID())) {
             return;
         }
-        component.gameScores().put(game, score);
+        Map<String, Integer> scores = new HashMap<>(component.gameScores());
+        scores.put(game, score);
+        component = new BestScoreComponent(Map.copyOf(scores), component.stringUUID());
         stack.set(DataComponentRegistry.BEST_SCORE, component);
     }
```

**Comment by wolfieboy09** [comment]
![image](https://github.com/user-attachments/assets/9e7493ca-4d0f-4ad7-ade7-d93af7ecc1f5)
I have updated the code, but had to change a line because you can't do `stack.get(DataComponentRegistry.BEST_SCORE, new BestScoreComponent(...));`

**Comment by EnderTurret** [comment]
Ah, it looks like I made a typo — that should be `stack.getOrDefault(...)`. The new code from what I can tell now introduces a different issue wherein high scores can't be set on new consoles (since the data component is `null` in that case). Changing the `stack.get()` call to `stack.getOrDefault()` should fix that (and you'll be able to remove the `null` check too).

**Comment by wolfieboy09** [comment]
Oh hey, getOrDefault is a thing

**Comment by EnderTurret** [comment]
I've now tested the changes locally and they seem to work fine — leaving and rejoining a world no longer prevents setting new high scores.
